version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./.database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicine
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  php:
    build: ./docker
    volumes:
      - ./:/app
    depends_on:
      - mysql
  nginx:
    image: 'nginx:alpine'
    restart: always
    volumes:
      - './docker//nginx.template:/etc/nginx/conf.d/nginx.template'
      - './:/app'
      - './.logs/nginx:/var/log/nginx'
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=med.loc
      - NGINX_PORT=80
    command: sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
